name: Validate dog-gifts.json

on:
  push:
    branches: [ main ]
    paths: [ 'dog-gifts.json', 'dog-gifts.schema.json', '.github/workflows/validate-json.yml' ]
  pull_request:
    paths: [ 'dog-gifts.json', 'dog-gifts.schema.json' ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check JSON parses
        run: |
          python - <<'PY'
          import json
          json.load(open('dog-gifts.json','r',encoding='utf-8'))
          print("OK: JSON parses")
          PY

      - name: Install jsonschema
        run: pip install jsonschema

      - name: Validate against schema
        run: |
          python - <<'PY'
          import json, sys
          from jsonschema import Draft202012Validator
          data = json.load(open('dog-gifts.json','r',encoding='utf-8'))
          schema = json.load(open('dog-gifts.schema.json','r',encoding='utf-8'))
          v = Draft202012Validator(schema)
          errors = sorted(v.iter_errors(data), key=lambda e: e.path)
          if errors:
              for e in errors:
                  loc = "/".join(map(str,e.path)) or "<root>"
                  print(f"SCHEMA ERROR at {loc}: {e.message}")
              sys.exit(1)
          print("OK: Schema validation passed")
          PY
